### ISSUE TITLE
Ensure EbisuHowto.ipynb runs to completion as part of test/build release

### ISSUE THREAD

**Issue by fasiha** [fasiha/ebisu#13]
Twice now I've published a version with a broken IPython Notebook demo. How to automatically test this?

**Comment by AlexRiina** [comment]
One way might be running
```
jupyter nbconvert --to notebook --execute EbisuHowto.ipynb
```
inside of a github action [per nbconverts docs](https://nbconvert.readthedocs.io/en/latest/execute_api.html#executing-notebooks-from-the-command-line). Not sure if there's a way to do it without the side-effect output file.

**Comment by fasiha** [comment]
Excellent, thank you so much! I've put this in the testing/bundling pipeline, that should hopefully remind me to check it next time I publish a new version.
